defaultMode: "ambilight"
capturerType: "dxgi"
server:
  host: "192.168.1.101"
  port: 4197
  leds: 150
  stripType: "grb"
  gpioPin: 18
  brightness: 255
displays:
- leds: 100
  bounds:
    from:
      x: 1
      y: 2
    to:
      x: 3
      y: 4
- leds: 50
  bounds:
    from:
      x: 5
      y: 6
    to:
      x: 7
      y: 8
